update logic

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -42,11 +42,16 @@ add-worker:
   script:
     - yamllint --strict ${YAML_PATH} || LINT_STATUS=$?
     - |
-      if [ ${LINT_STATUS} -eq 2 ] && [ "${ALLOW_WARNINGS}" = true ]; then
-        echo "Error: YAML warnings detected, ignoring"
+      if [ $LINT_STATUS -eq 0 ]; then
         exit 0
       else
-        exit ${LINT_STATUS}
+        if [ ${LINT_STATUS} -eq 2 ] && [ "${ALLOW_WARNINGS}" = true ]; then
+          echo -e "YAML warnings detected: ignoring because \"ALLOW_WARNINGS\" is set to \"true\""
+          exit 0
+        else
+          echo -e "Error: One or more errors and warnings detected"
+          exit ${LINT_STATUS}
+        fi
       fi
 
 ansible-roles:
